/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.gradle.basics;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

@Tag("individual")
public class AppTest1 {
    @Test
    public void test() {
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException ignored) {
        }
    }
}
