/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab.gradle.basics;

import org.junit.jupiter.api.*;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;

@Tag("together")
public class AppTest {
    private long start;
    private static long startAll;

    @BeforeAll
    static void beforeAll() {
        startAll = Instant.now().toEpochMilli();
    }

    @AfterAll
    static void afterAll() {
        long endAll = Instant.now().toEpochMilli();
        System.out.println("Total time: " +
                (endAll - startAll) + "ms");
    }

    @BeforeEach
    void setUp() {
        start = Instant.now().toEpochMilli();
    }

    @AfterEach
    void tearDown(TestInfo testInfo) {
        long end = Instant.now().toEpochMilli();
        String name = testInfo.getDisplayName();
        System.out.println("Test " + name + " started at " +
                epoch2LDT(start) + " ended at " +
                epoch2LDT(end) + ": (" + (end - start) + "ms)");
    }

    private LocalDateTime epoch2LDT(long time) {
        return Instant.ofEpochMilli(time)
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();
    }

    @Test
    public void test1() {
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException ignored) {
        }
    }

    @Test
    public void test2() {
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException ignored) {
        }
    }

    @Test
    public void test3() {
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException ignored) {
        }
    }

    @Test
    public void test4() {
        try {
            Thread.sleep(1000L);
        } catch (InterruptedException ignored) {
        }
    }
}
